flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- HDBC-sqlite3-2.3.3.1
- HUnit-1.3.0.0
- QuickCheck-2.8.1
- aeson-0.9.0.1
- ansi-terminal-0.6.2.2
- async-2.0.2
- attoparsec-0.13.0.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.0
- blaze-markup-0.7.0.2
- byteable-0.1.1
- convertible-1.1.1.0
- cryptohash-0.11.6
- dlist-0.7.1.2
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- happstack-server-7.4.4
- hashable-1.2.3.3
- hslogger-1.2.9
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- html-1.0.1.2
- json-0.9.1
- monad-control-1.0.0.4
- mtl-2.2.1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- primitive-0.6
- quickcheck-io-0.1.2
- random-1.1
- scientific-0.3.3.8
- sendfile-0.7.9
- setenv-0.1.1.3
- stm-2.4.4
- syb-0.5.1
- system-filepath-0.4.13.4
- text-1.2.1.3
- tf-random-0.5
- threads-0.5.1.3
- time-compat-0.1.0.3
- transformers-0.4.3.0
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- zlib-0.6.1.1
resolver: ghc-7.10.2
